version: '3.8'

services:
  frontend:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    command: sh -c "npm install && npm run dev -- --host"